### ISSUE TITLE
What is classnames ?

### ISSUE THREAD

**Issue by iroshiva** [MarieComet/core-block-custom-attributes#1]
Hi Marie,

Thanks very much for the repository !

One question: what is classnames in import classnames from 'classnames' ???

Thx

**Comment by MarieComet** [comment]
classnames is a JavaScript utility to manage class : https://www.npmjs.com/package/classnames
It's used to assign classes depending on block attribute : https://github.com/MarieComet/core-block-custom-attributes/blob/main/src/attributes/sidebarSelect.js#L132

**Comment by iroshiva** [comment]
Cool !
Thank you very much !

I didn't see it in the package.json ;)

**Comment by MarieComet** [comment]
Ah yes !
Maybe it's included by @wordpress/scripts, I don't know :)
