### ISSUE TITLE
Cannot build the package.

### ISSUE THREAD

**Issue by tiennguyenvan** [MarieComet/core-block-custom-attributes#2]
Hello Marie,

I ran the build command and here is the error: 
![image](https://user-images.githubusercontent.com/12868514/209430827-511702b4-89fe-4c56-8919-c0158970bc43.png)

Hope you could help. Thank you very much.

**Comment by ibrokemycomputer** [comment]
@tiennguyenvan You need to use Node 16, it errors on newer versions.

**Comment by tiennguyenvan** [comment]
> @tiennguyenvan You need to use Node 16, it errors on newer versions.

Thank you. I used the wrong command so it could not build.

**Comment by aiac** [comment]
Do not downgrade. It`s a security related problem with dependencies, something about SSL.

Do `npm audit fix --force` instead.
